auth:
  login: "TolkunovMA2"
  password: "turtlew001"
  telegram_token: "7900350947:AAH6HwpS3cul80lpRrfBCZYcfV1UcsVzhfY"
  telegram_chat_id: "448432243"

search:
  good_words:
    - "МК"
    - "сайт"
    - "программирование"
    - "схемотехника"
    - "диз"
    - "разраб"
    - "создание"
  bad_words:
    - "врач"

settings:
  refresh_interval: 60
  batch_size: 10
  scroll_pause_time: 2
