auth:
  login: "REDACTED_LOGIN"
  password: "REDACTED_PASSWORD"
  telegram_token: "REDACTED_TELEGRAM_TOKEN"
  telegram_chat_id: "REDACTED_CHAT_ID"

search:
  good_words:
    - "МК"
    - "сайт"
    - "программирование"
    - "схемотехника"
    - "диз"
    - "разработка"
    - "создание"
  bad_words:
    - "врач"

settings:
  refresh_interval: 120                              # Интервал отправки сообщений в Телеграм (в секундах)
  batch_size: 10                                     # Количество задач, которые будут отправлены за один запрос
  scroll_pause_time: 2                               # Время ожидания между прокрутками страницы (в секундах)
  night_start_hour: 23                               # Час начала ночного режима
  night_end_hour: 7                                  # Час окончания ночного режима

chrome:
  cookies_file: "session"                            # Файл с куками
  headless: False                                    # Режим работы браузера (True - без графического интерфейса, False - с графическим интерфейсом)
